student/urls.py
from django.urls import path
from student import views as student_views

app_name = 'student'

urlpatterns = [
    path('', student_views.dashboard, name='dashboard'),

    path('student_profile_dash_form/', student_views.studentProfileDashView, name='student_profile_dash_form'),
    # path('edit-profile/', student_views.edit_profile, name='edit_profile'),
    # path('marks/', student_views.createMarkSheetView, name='add_marks'),
    # path('basic-details/', student_views.createExtraInfoView, name='basic_details'),
    # path('workexperience/', student_views.WorkExperienceView, name='work_experience'),
    # path('deleteworkexperience/<int:pk>/', student_views.deleteWorkExperienceView, name='delete_work_experience'),
   # path('school-education/', student_views.schoolEducation, name='school-education'),

    path('school-education/<int:pk>/', student_views.schoolEducation, name='school-education'),
    # path('college-education/', student_views.collegeEducation, name='college-education'),
    path('work-exp/<category>/', student_views.workExperienceDashView, name='work-exp'),
    path('work-exp/', student_views.workExperienceDashView, name='work-exp'),
    path('work-exp/edit/<int:pk>/', student_views.editWorkExperienceDashView, name='work-exp-edit'),
    path('work-exp/delete/<int:pk>/', student_views.workExperienceDelete, name='work-exp-delete'),

    path('college-education/', student_views.collegeEducationDashView, name='college-education'),
    path('college-education/<course>/', student_views.collegeEducationDashView, name='college-education'),
    path('college-education/edit/<pk>/', student_views.collegeEducationEdit, name='college-education-edit'),
    path('college-education/delete/<pk>/', student_views.collegeEducationDelete, name='college-education-delete'),

    path('marksheet/edit/<int:pk>/', student_views.marksheetEdit, name='marksheet-edit'),


]

tnp/urls.py
from django.contrib import admin
from django.urls import path, include, reverse, reverse_lazy
from account import views as account_views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('api/', include('api.endpoints')),
    path('api/auth', include('knox.urls')),
    path('account/', include('account.urls')),
    path('student/', include('student.urls')),
    path('faculty/', include('faculty.urls')),
    path('activate/<uidb64>[0-9A-Za-z_\-]+/<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20}', account_views.activate, name='activate'),
    path('password_reset/', auth_views.PasswordResetView.as_view(success_url=reverse_lazy('password_reset_done')), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password_reset/confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset/complete/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

student/models.py
from django.db import models
from django.conf import settings
from django.utils.translation import ugettext_lazy as _
from django.core.validators import MaxValueValidator, MinValueValidator

from datetime import datetime

class StudentProfile(models.Model):
    class Meta:
        verbose_name = "Student Profile"

    COLLEGE = (
        ('USICT', 'U.S.I.C.T.'),
    )

    COURSE = (
        ('B.TECH - CSE', 'B.TECH - CSE'),
        ('B.TECH - IT', 'B.TECH - IT'),
        ('B.TECH - ECE', 'B.TECH - ECE'),
        ('M.TECH - CSE', 'M.TECH - CSE'),
        ('M.TECH - IT', 'M.TECH - IT'),
        ('M.TECH - ECE', 'M.TECH - ECE'),
        ('MCA', 'MCA'),
    )

    ADMISSION_YEAR_CHOICES = []
    for r in range((datetime.now().year-4), (datetime.now().year+1)):
        ADMISSION_YEAR_CHOICES.append((r,r))

    PASSING_YEAR_CHOICES = []
    for r in range((datetime.now().year), (datetime.now().year+5)):
        PASSING_YEAR_CHOICES.append((r,r))

    REGION = (
        ('Delhi', 'Delhi'),
        ('Outside Delhi', 'Outside Delhi'),
    )

    CATEGORY = (
        ('Unreserved', 'Unreserved'),
        ('OBC', 'OBC'),
        ('SC', 'SC'),
        ('ST', 'ST'),
        ('OTH', 'Other'),
    )

    GENDER = (
        ('Male', 'Male'),
        ('Female', 'Female'),
        ('Others', 'Others'),
    )

    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    enrollment_no = models.CharField(max_length=20, unique=True, null=False, blank=False)
    name = models.CharField(_("Full Name"), max_length=100)
    gender = models.CharField(max_length=11, choices=GENDER)
    date_of_birth = models.DateField(_("Date of birth"), blank=True, null=True)
    college = models.CharField(max_length=10,choices=COLLEGE,default='USICT')
    #institute_code = models.IntegerField(default=0)
    #program_code = models.IntegerField(default=0)
    course = models.CharField(max_length = 20, choices=COURSE)
    admission_year = models.IntegerField(_('Year of Admission'), blank=True, null=True, choices=ADMISSION_YEAR_CHOICES)
    passing_year = models.IntegerField(_('Year of Passing Out'), blank=True, null=True, choices=PASSING_YEAR_CHOICES)
    fathers_name = models.CharField(max_length=100, blank=True, null=True)
    region = models.CharField(max_length=20, choices=REGION)
    category = models.CharField(max_length=20, choices=CATEGORY)
    primary_mobile = models.PositiveIntegerField(_("Mobile Number"), blank=True, null=True, validators=[MaxValueValidator(9999999999)])
    secondary_mobile = models.PositiveIntegerField(_("Alternative Mobile Number"), blank=True, null=True, validators=[MaxValueValidator(9999999999)])
    address = models.TextField(max_length=200, blank=True, null=True)

    def __str__(self):
        return self.user.email

class ExtraInfo(models.Model):

    EDUCATION = (
        ('UP TO 5TH', 'UP TO 5TH'),
        ('UP TO 8TH', 'UP TO 8TH'),
        ('UP TO 10TH', 'UP TO 10TH'),
        ('UP TO 12TH', 'UP TO 12TH'),
        ('UP TO UG', 'UP TO UG'),
        ('UP TO PG', 'UP TO PG'),
        ('ANY OTHER', 'ANY OTHER'),
    )

    FAMILY_INCOME = (
        ('< 50,000', '< 50,000'),
        ('50,000 - 1,00,000', '50,000 - 1,00,000'),
        ('1,00,000 - 2,50,000', '1,00,000 - 2,50,000'),
        ('2,50,000 - 4,00,000', '2,50,000 - 4,00,000'),
        ('4,00,000 - 6,00,000', '4,00,000 - 6,00,000'),
        ('6,00,000 - 10,00,000', '6,00,000 - 10,00,000'),
        ('10,00,000 >', '10,00,000 >'),
    )

    SCHOOL_ATTENDED_12TH = (
        ('GOVT', 'GOVT'),
        ('GOVT AIDED', 'GOVT AIDED'),
        ('SELF FINANCING/ UNAIDED', 'SELF FINANCING/ UNAIDED'),
    )

    BOARD = (
        ('CBSE', 'CBSE'),
        ('State Board', 'State Board'),
        ('NIOS', 'NIOS'),
        ('Madarsa', 'Madarsa'),
        ('Other', 'Other'),
    )

    FATHERS_EMPLOYMENT = (
        ('GOVT Service, PSU', 'GOVT Service, PSU'),
        ('Private service', 'Private service'),
        ('Self employed', 'Self employed'),
        ('Professional', 'Professional'),
        ('Casual Labour', 'Casual Labour'),
        ('Farming, Agri-Labour', 'Farming, Agri-Labour'),
        ('Unemployed', 'Unemployed'),
        ('Other', 'Other'),
    )

    MOTHERS_EMPLOYMENT = (
        ('GOVT Service, PSU', 'GOVT Service, PSU'),
        ('Private service', 'Private service'),
        ('Self employed', 'Self employed'),
        ('Professional', 'Professional'),
        ('Casual Labour', 'Casual Labour'),
        ('Farming, Agri-Labour', 'Farming, Agri-Labour'),
        ('House wife', 'House wife'),
        ('Other', 'Other'),
    )

    RELIGION = (
        ('Hindu', 'Hindu'),
        ('Muslim', 'Muslim'),
        ('Sikh', 'Sikh'),
        ('Christain', 'Christain'),
        ('Jain', 'Jain'),
        ('Buddhist', 'Buddhist'),
        ('Parshi', 'Parshi'),
        ('Any other', 'Any other'),
    )

    student = models.OneToOneField(StudentProfile, on_delete=models.CASCADE)
    address = models.CharField(max_length=1024, blank=True, null=True)
    pincode = models.IntegerField(blank=True, null=True)
    fathers_education = models.CharField(max_length=20, choices=EDUCATION, blank=True, null=True)
    mothers_education = models.CharField(max_length=20, choices=EDUCATION, blank=True, null=True)
    family_income = models.CharField(max_length=20, choices=FAMILY_INCOME, blank=True, null=True)
    school_attended_12th = models.CharField(max_length=20, choices=SCHOOL_ATTENDED_12TH, blank=True, null=True)
    board = models.CharField(max_length=20, choices=BOARD, blank=True, null=True)
    aadhar_number = models.IntegerField(blank=True, null=True, validators=[MaxValueValidator(9999999999999999)])
    religion = models.CharField(max_length=20, choices=RELIGION, blank=True, null=True)
    fathers_employment = models.CharField(max_length=20, choices=FATHERS_EMPLOYMENT, blank=True, null=True)
    mothers_employment = models.CharField(max_length=20, choices=MOTHERS_EMPLOYMENT, blank=True, null=True)


    def __str__(self):
        return self.student.enrollment_no

class MarkSheet(models.Model):
    student = models.OneToOneField(StudentProfile, on_delete=models.CASCADE)
    semester_1 = models.DecimalField(max_digits=5, decimal_places=3, validators=[MaxValueValidator(10.000),MinValueValidator(0.000)],blank=True, null=True)
    semester_2 = models.DecimalField(max_digits=5, decimal_places=3, validators=[MaxValueValidator(10.000),MinValueValidator(0.000)],blank=True, null=True)
    semester_3 = models.DecimalField(max_digits=5, decimal_places=3, validators=[MaxValueValidator(10.000),MinValueValidator(0.000)],blank=True, null=True)
    semester_4 = models.DecimalField(max_digits=5, decimal_places=3, validators=[MaxValueValidator(10.000),MinValueValidator(0.000)],blank=True, null=True)
    semester_5 = models.DecimalField(max_digits=5, decimal_places=3, validators=[MaxValueValidator(10.000),MinValueValidator(0.000)],blank=True, null=True)
    semester_6 = models.DecimalField(max_digits=5, decimal_places=3, validators=[MaxValueValidator(10.000),MinValueValidator(0.000)],blank=True, null=True)
    semester_7 = models.DecimalField(max_digits=5, decimal_places=3, validators=[MaxValueValidator(10.000),MinValueValidator(0.000)],blank=True, null=True)
    semester_8 = models.DecimalField(max_digits=5, decimal_places=3, validators=[MaxValueValidator(10.000),MinValueValidator(0.000)],blank=True, null=True)
    cgpa = models.DecimalField(max_digits=5, decimal_places=3, validators=[MaxValueValidator(10.000),MinValueValidator(0.000)],blank=True, null=True)

    credits_skipped = models.IntegerField(validators=[MinValueValidator(0)], blank=True, null=True)
    backlogs = models.IntegerField(verbose_name = "Number of Backlogs", validators=[MinValueValidator(0)], blank=True, null=True)

    def __str__(self):
        return self.student.enrollment_no
        #return "%s "%s" % (self.student.enrollment_no, self.student.name)

class WorkExperience(models.Model):

    CATEGORY_CHOICE =(
        ('Internship', 'Internship'),
        ('Project', 'Project'),
        ('Training', 'Training'),
        ('Achievement', 'Achievement'),
        ('Other', 'Other'),
    )

    student = models.ForeignKey(StudentProfile, on_delete=models.CASCADE)
    category = models.CharField(choices = CATEGORY_CHOICE, max_length = 15, null=True)
    title = models.CharField(max_length = 50, null=True)
    start_date = models.DateField(_("Starting Date"), null=True)
    end_date = models.DateField(_("Ending Date"), blank=True, null=True)
    url = models.URLField(blank=True, null=True)
    description = models.TextField(max_length = 200, null=True)

    def __str__(self):
        return self.student.enrollment_no

class SchoolEducation(models.Model):

    QUALIFICATION_CHOICE = (
        ('HighSchool', 'High School'),
        ('SeniorSecondary', 'Senior Secondary'),
    )

    YEAR_CHOICES = []
    for r in range((datetime.now().year-15), (datetime.now().year+1)):
        YEAR_CHOICES.append((r,r))

    student = models.ForeignKey(StudentProfile, on_delete=models.CASCADE)
    qualification = models.CharField(choices=QUALIFICATION_CHOICE, max_length=20, null=True)
    year = models.IntegerField(choices=YEAR_CHOICES, null=True, blank=True)
    board = models.CharField(max_length=50, null=True, blank=True)
    school = models.CharField(max_length=100, null=True, blank=True)
    marks = models.CharField(_("Percentage/CGPA"), max_length=5, null=True, blank=True)

    def __str__(self):
        return self.student.enrollment_no

class CollegeEducation(models.Model):
    ADMISSION_YEAR_CHOICES = []
    for r in range((datetime.now().year-4), (datetime.now().year+1)):
        ADMISSION_YEAR_CHOICES.append((r,r))

    PASSING_YEAR_CHOICES = []
    for r in range((datetime.now().year), (datetime.now().year+5)):
        PASSING_YEAR_CHOICES.append((r,r))

    COURSES = (
        ('Graduation', 'Graduation'),
        ('Post-Graduation', 'Post-Graduation'),
        ('PhD', 'PhD'),

student/forms.py
from django import forms
from django.forms.widgets import HiddenInput
from student.models import (
    StudentProfile,
    MarkSheet,
    ExtraInfo,
    WorkExperience,
    SchoolEducation,
    CollegeEducation,
    )
class DateInput(forms.DateInput):
    input_type = 'date'


class StudentProfileDashForm(forms.ModelForm):
    date_of_birth = forms.DateField(required = True, widget = DateInput())

    class Meta:
        model = StudentProfile
        exclude = ['user', 'enrollment_no', 'college', 'course', 'admission_year','passing_year', 'name']
        widgets = {
            'fathers_name': forms.TextInput(attrs={'required': 'true', 'placeholder': 'Father\'s name'}),
            'primary_mobile': forms.TextInput(attrs={'required': 'true', 'placeholder': 'Mobile number'}),
            'secondary_mobile': forms.TextInput(attrs={'placeholder': 'Alternate mobile number'}),
            'address': forms.Textarea(attrs={'required': 'true', 'placeholder': 'Address'}),

        }

class MarkSheetForm(forms.ModelForm):

    class Meta:
        model = MarkSheet
        exclude = ['student',]

class ExtraInfoForm(forms.ModelForm):
    class Meta:
        model = ExtraInfo
        exclude = ['student',]

class WorkExperienceForm(forms.ModelForm):
    start_date = forms.DateField(required = False, widget = DateInput())
    end_date = forms.DateField(required = False, widget = DateInput())
    category = forms.CharField(widget=HiddenInput)

    class Meta:
        model = WorkExperience
        exclude = ['student',]
        widgets = {
            'title': forms.TextInput(attrs={'required': 'true', 'placeholder': 'Title or company name'}),
            # 'url': forms.TextInp       ut(attrs={'required': 'true', 'placeholder': 'School name'}),
            # '': forms.TextInput(attrs={'placeholder': 'Alternate mobile number'}),
            'description': forms.Textarea(attrs={'required': 'true', 'placeholder': 'Describe your experience'}),
        }


class WorkExperienceEditForm(forms.ModelForm):
    start_date = forms.DateField(required = False, widget = DateInput())
    end_date = forms.DateField(required = False, widget = DateInput())

    class Meta:
        model = WorkExperience
        exclude = ['student', 'category']
        widgets = {
            'title': forms.TextInput(attrs={'required': 'true', 'placeholder': 'Title or company name'}),
            # 'url': forms.TextInp       ut(attrs={'required': 'true', 'placeholder': 'School name'}),
            # '': forms.TextInput(attrs={'placeholder': 'Alternate mobile number'}),
            'description': forms.Textarea(attrs={'required': 'true', 'placeholder': 'Describe your experience'}),

        }


class SchoolEducationForm(forms.ModelForm):
    class Meta:
        model = SchoolEducation
        exclude = ['student', 'qualification']
        widgets = {
            'board': forms.TextInput(attrs={'required': 'true', 'placeholder': 'School board'}),
            'school': forms.TextInput(attrs={'required': 'true', 'placeholder': 'School name'}),
            # '': forms.TextInput(attrs={'placeholder': 'Alternate mobile number'}),
            'marks': forms.TextInput(attrs={'required': 'true', 'placeholder': 'Percentage or CGPA'}),

        }

class CollegeEducationForm(forms.ModelForm):
    course = forms.CharField(widget=HiddenInput)

    class Meta:
        model = CollegeEducation
        exclude = ['student', 'from_profile']
        widgets = {
            'branch': forms.TextInput(attrs={'required': 'true', 'placeholder': 'Course name'}),
            'college': forms.TextInput(attrs={'required': 'true', 'placeholder': 'College name'}),
            # '': forms.TextInput(attrs={'placeholder': 'Alternate mobile number'}),
            'marks': forms.NumberInput(attrs={'required': 'true', 'placeholder': 'Percentage or CGPA', 'step': 0.01}),

        }

templates/student/add_extra_info.html
{% extends '../home/base.html' %}
{% block body %}
{% include './stud_nav.html' %}

<div class="row">
  <div class="col s6 offset-s3">
    <br><br>
  <div class="card center lime lighten-5 z-depth-5">
    <div class="card-inner">
      <h5 class="login">Basic details</h5>


<form method="post">
  {% csrf_token %}
  {{ extra_info_form.as_p }}

  <input type="submit" class="btn" value="Submit">

</form>

</div>
</div>
</div>
</div>

{% endblock %}

templates/student/edit_profile.html
{% extends '../home/base.html' %}
{% block body %}
{% include './stud_nav.html' %}

<div class="row">
  <div class="col s6 offset-s3">
    <br><br>
  <div class="card center lime lighten-5 z-depth-5">
    <div class="card-inner">
      <h5 class="login">Edit Profile</h5>


<form method="post">
  {% csrf_token %}
  {{ student_profile_form.as_p }}

  <input type="submit" class="btn" value="Submit">

</form>

</div>
</div>
</div>
</div>

{% endblock %}

templates/student/stud_nav.html
<div class="stud_nav">
  <nav class="indigo darken-3">
    <div class="navbar-wrapper">
      <ul>
        <li><a href="{% url 'student:dashboard' %}" class="">Dashboard</a></li>

      </ul>

      <ul class="center right">
        <li><a href="{% url 'student:edit_profile' %}" class="">Personal Info</a></li>
        <li><a href="{% url 'student:basic_details' %}" class="">Basic details</a></li>
        <li><a href="{% url 'student:add_marks' %}" class="">Add/Update marks</a></li>
        <li><a href="{% url 'student:education' %}" class="">Education</a></li>
        <li><a href="{% url 'student:work_experience' %}" class="">Work Experience</a></li>
        


      </ul>
  </div>

  </nav>
</div>


<style media="screen">

.stud_nav nav {
    height: 40px;
    line-height: 40px;
}

.stud_nav nav i, .stud_nav nav [class^="mdi-"], .stud_nav nav [class*="mdi-"], .stud_nav nav i.material-icons {
    height: 40px;
    line-height: 40px;
}

.stud_nav nav .button-collapse i {
    height: 40px;
    line-height: 40px;
}

.stud_nav nav .brand-logo {
    font-size: 1.6rem;
}

@media only screen and (min-width: 601px){
    .stud_nav nav, .stud_nav nav .nav-wrapper i, .stud_nav nav a.button-collapse, .stud_nav nav a.button-collapse i {
        height: 40px;
        line-height: 40px;
    }
}

</style>

templates/student/work_experience.html
{% extends '../home/base.html' %}
{% block body %}
{% include './stud_nav.html' %}


<!-- --------------------------- INTERNSHIP SECTION ------------------------------------>
<section class="internship">
<div class="row">
  <div class="col s6 offset-s3">
    <br><br>
  <div class="card center lime lighten-5 z-depth-5">
    <div class="card-inner">
      <h4>INTERNSHIPS</h4>

        {% for work_experience in work_experience_all %}
        {% if work_experience.category == 'Internship' %}
          <div>
            <p>Title: {{ work_experience.title }}</p>
            <p>Start Date: {{ work_experience.start_date }}
            <p>End Date: {{ work_experience.end_date }}</p>
            <p>Url: {{ work_experience.url }}</p>
            <p>Description: {{ work_experience.description }}</p>
            <a class="modal-trigger edit-experience-modal-btn" data-value="{{ work_experience.pk }}" href="#modal2">Edit</a> |
            <a href="#" class="delete-btn" data-value="{{ work_experience.pk }}" >Delete</a><br><br>
          </div>
        {% endif %}
        {% endfor %}

        <a class="modal-trigger add-experience-modal-btn" href="#modal1" id="add-internship-modal-btn" data-value="Internship" >Add Internship</a>

</div>
</div>
</div>
</div>
</section>
<!--------------------------    INTERNSHIP SECTION END -------------------------------------->

<!-- --------------------------- TRAINING SECTION ------------------------------------>
<section class="internship">
<div class="row">
  <div class="col s6 offset-s3">
    <br><br>
  <div class="card center lime lighten-5 z-depth-5">
    <div class="card-inner">
      <h4>TRAININGS</h4>

        {% for work_experience in work_experience_all %}
        {% if work_experience.category == "Training" %}
          <div>
            <p>Title: {{ work_experience.title }}</p>
            <p>Start Date: {{ work_experience.start_date }}
            <p>End Date: {{ work_experience.end_date }}</p>
            <p>Url: {{ work_experience.url }}</p>
            <p>Description: {{ work_experience.description }}</p>
            <a class="modal-trigger edit-experience-modal-btn" data-value="{{ work_experience.pk }}" href="#modal2">Edit</a> |
            <a href="#" class="delete-btn" data-value="{{ work_experience.pk }}" >Delete</a><br><br>
          </div>
        {% endif %}
        {% endfor %}

        <a class="modal-trigger add-experience-modal-btn" href="#modal1" id="add-training-modal-btn"  data-value="Training">Add Training</a>

</div>
</div>
</div>
</div>
</section>
<!--------------------------    TRAINING SECTION END -------------------------------------->

<!-- --------------------------- PROJECT SECTION ------------------------------------>
<section class="internship">
<div class="row">
  <div class="col s6 offset-s3">
    <br><br>
  <div class="card center lime lighten-5 z-depth-5">
    <div class="card-inner">
      <h4>PROJECTS</h4>

        {% for work_experience in work_experience_all %}
        {% if work_experience.category == "Project" %}
          <div>
            <p>Title: {{ work_experience.title }}</p>
            <p>Start Date: {{ work_experience.start_date }}
            <p>End Date: {{ work_experience.end_date }}</p>
            <p>Url: {{ work_experience.url }}</p>
            <p>Description: {{ work_experience.description }}</p>
            <a class="modal-trigger edit-experience-modal-btn" data-value="{{ work_experience.pk }}" href="#modal2">Edit</a> |
            <a href="#" class="delete-btn" data-value="{{ work_experience.pk }}" >Delete</a><br><br>
          </div>
        {% endif %}
        {% endfor %}

        <a class="modal-trigger add-experience-modal-btn" href="#modal1" id="add-project-modal-btn"  data-value="Project">Add project</a>

</div>
</div>
</div>
</div>
</section>
<!--------------------------    PROJECT SECTION END -------------------------------------->

<!-- --------------------------- ACHIEVEMENT SECTION ------------------------------------>
<section class="internship">
<div class="row">
  <div class="col s6 offset-s3">
    <br><br>
  <div class="card center lime lighten-5 z-depth-5">
    <div class="card-inner">
      <h4>ACHIEVEMENTS</h4>

        {% for work_experience in work_experience_all %}
        {% if work_experience.category == "Achievements" %}
          <div>
            <p>Title: {{ work_experience.title }}</p>
            <p>Start Date: {{ work_experience.start_date }}
            <p>End Date: {{ work_experience.end_date }}</p>
            <p>Url: {{ work_experience.url }}</p>
            <p>Description: {{ work_experience.description }}</p>
            <a class="modal-trigger edit-experience-modal-btn" data-value="{{ work_experience.pk }}" href="#modal2">Edit</a> |
            <a href="#" class="delete-btn" data-value="{{ work_experience.pk }}" >Delete</a><br><br>
          </div>
        {% endif %}
        {% endfor %}

        <a class="modal-trigger add-experience-modal-btn" href="#modal1" id="add-achievement-modal-btn"  data-value="Achievement">Add Achievement</a>

</div>
</div>
</div>
</div>
</section>
<!--------------------------    ACHIEVEMENT SECTION END -------------------------------------->



  <!--Work Experience Modal Structure -->
  <div id="modal1" class="modal">
      <form method="post" id="add-work-experience-form">
          <div class="modal-content">
              <h5>Work Experience Details</h5>
            </div>
          {% csrf_token %}
          <div class ="form-goes-here">{{ work_experience_form.as_p }}</div>
          <div class="modal-footer">
          <div><input type="submit" class="btn" id="submit-btn" value="Submit"></div>
            </div>
          
        
        </form>
  </div>

  <!--Edit Experience Modal Structure -->
  <div id="modal2" class="modal">
      <form method="post" id="edit-work-experience-form">
          <div class="modal-content">
              <h5>Add Details</h5>
            </div>
          {% csrf_token %}
          <div id="edit-form-goes-here"></div>
          <div class="modal-footer">
          <div id="form-btn-goes-here"><input type="submit" class="btn" id="edit-form-submit-btn" value="Submit"></div>
            </div>
          
        
        </form>
  </div>






<!--------------------------  WORK EXPERIENCE SCRIPT --------------------------------->
 <script>
      $(document).ready(function(){

        $('.add-experience-modal-btn').click(function(){
          $('.modal').modal();
          var category = $(this).data("value");
          $('#add-work-experience-form #id_category').val(category);
        });


        /* EDIT WORK EXPERIENCE GET REQUEST */
        pk=0;
        $('.edit-experience-modal-btn').click(function(){
          pk = ($(this).data("value"));
          var url = '{% url "student:edit_work_experience"  000 %}'.replace(000, pk);
          $.ajax({
                   type: "GET",
                   url: url,
                   success: function(data)
                   {      
                       $('#edit-form-goes-here').html(data);
                   }
      
                 });
          $('.modal').modal();
        });


         /* EDIT WORK EXPERIENCE POST REQUEST */
        $('#edit-work-experience-form').submit(function(e){
          e.preventDefault();
          var url = '{% url "student:edit_work_experience"  pk=000 %}'.replace(000, pk);
          form = $(this); 
          $.ajax({
                   type: "POST",
                   url: url,
                   data : form.serialize(),
                   success: function(data)
                   {
                       console.log('edit successful');
                   }
                 });
        location.reload();
        });

        /* DELETE WORK EXPERIENCE */
        $('.delete-btn').click(function(e){
          e.preventDefault();
          var response = confirm('Are you sure you want to delete this work experience');
          if(response === true){
          var pk1 = ($(this).data("value"));
          var url = '{% url "student:delete_work_experience"  pk=000 %}'.replace(000, pk1);
          $.ajax({
            type: "GET",
            url: url,
            success: function(data){
              console.log(data);
            }
          });
          location.reload();
        }
        });

      });
    </script>
<!--------------------------------------- WORK EXPERIENCE SCRIPT END ----------------------------------------------->

  {% endblock %}
  