account/urls.py
from django.urls import path, reverse, reverse_lazy
from account import views as account_views
from django.contrib.auth import views as auth_views

app_name = 'account'

urlpatterns = [
    path('register/', account_views.student_register, name='student_register'),
    path('login/', account_views.student_login, name='student_login'),
    path('logout/', account_views.user_logout, name='logout'),
    path('faculty_register/', account_views.faculty_register, name='faculty_register'),
    path('faculty_login/', account_views.faculty_login, name='faculty_login'),
 
]

home/urls.py
from django.urls import path
from home import views as home_views

app_name = 'home'

urlpatterns = [
     path('', home_views.index, name='index'),
]

tnp/urls.py
from django.contrib import admin
from django.urls import path, include, reverse, reverse_lazy
from account import views as account_views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('api/', include('api.endpoints')),
    path('api/auth', include('knox.urls')),
    path('account/', include('account.urls')),
    path('student/', include('student.urls')),
    path('faculty/', include('faculty.urls')),
    path('activate/<uidb64>[0-9A-Za-z_\-]+/<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20}', account_views.activate, name='activate'),
    path('password_reset/', auth_views.PasswordResetView.as_view(success_url=reverse_lazy('password_reset_done')), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password_reset/confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset/complete/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

home/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
# Create your views here.
def index(request):
    return HttpResponseRedirect(reverse('account:student_login'))

templates/home/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    {% load staticfiles %}
    <!-- bootstrap CSS -->
    <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous"> -->
    <!-- bootstap js -->
    <!-- <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script> -->

    <!-- jquery -->
    <script src="https://code.jquery.com/jquery-3.3.1.js" integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60=" crossorigin="anonymous"></script>

    <!-- material Compiled and minified CSS -->
     <!-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">  -->

   <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.css">
   <script src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.js"></script>


    <!-- Compiled and minified JavaScript -->

    <!--material icons  -->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">


    <!-- custom css -->
    <link rel="stylesheet" href="{% static './css/style.css' %}">
    <link rel="shortcut icon" href="{% static 'img/ipu-logo.png' %}" />
    <title>Training and Placement Cell | USICT</title>
  </head>
  <body>
    {% include './navbar.html' %}
    {% block body %}
    {% endblock %}

  </body>
  <!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script> -->
  <!-- <script src="https://code.jquery.com/jquery-3.3.1.js" integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60=" crossorigin="anonymous"></script> -->



</html>

templates/home/index.html
{% extends './base.html' %}

{% block body %}
<h2 class="tag center">GURU GOBIND SINGH INDRAPRASTHA UNIVERSITY</h2>

<div class="pages center">

</div>
{% endblock %}

templates/home/navbar.html
{% load staticfiles %}
<nav class="">
  <div class="ui navbar menu">
    <a href="{% url 'home:index' %}" class="">
      <div class="ipu-brand">
        <img class="ipu_logo" src="{% static 'img/ipu-logo.png' %}" alt="ipu-logo">
        <p class="ipu-title-brand">Training & Placements Cell<br>
        University School of Information, Communication and Technology</p>
        <!-- <p class="ipu-title-brand">Guru Gobind Singh Indraprastha University</p> -->
      </div>

    </a>
    <ul id="nav-mobile" class="right menu" style="padding-right: 10px;">
      {% if user.is_authenticated %}
        <li class="navbar-right-menu"><a href="{% url 'account:logout' %}" class="ui button inverted primary">Logout</a></li>
      {% else %}
        <li class="navbar-right-menu"><a href="{% url 'account:student_login' %}" class="ui button inverted primary">Login/Register</a></li>
      {% endif %}

    </ul>
  </div>
</nav>