faculty/urls.py
from django.urls import path
from faculty import views as faculty_views

app_name = 'faculty'

urlpatterns = [
    path('', faculty_views.dashboard, name='dashboard'),
    path('filter', faculty_views.filter, name='filter'),
    path('student-detail/<enr>', faculty_views.studentDetail, name='student-detail'),
]

tnp/urls.py
from django.contrib import admin
from django.urls import path, include, reverse, reverse_lazy
from account import views as account_views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('api/', include('api.endpoints')),
    path('api/auth', include('knox.urls')),
    path('account/', include('account.urls')),
    path('student/', include('student.urls')),
    path('faculty/', include('faculty.urls')),
    path('activate/<uidb64>[0-9A-Za-z_\-]+/<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20}', account_views.activate, name='activate'),
    path('password_reset/', auth_views.PasswordResetView.as_view(success_url=reverse_lazy('password_reset_done')), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password_reset/confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset/complete/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

student/models.py
from django.db import models
from django.conf import settings
from django.utils.translation import ugettext_lazy as _
from django.core.validators import MaxValueValidator, MinValueValidator

from datetime import datetime

class StudentProfile(models.Model):
    class Meta:
        verbose_name = "Student Profile"

    COLLEGE = (
        ('USICT', 'U.S.I.C.T.'),
    )

    COURSE = (
        ('B.TECH - CSE', 'B.TECH - CSE'),
        ('B.TECH - IT', 'B.TECH - IT'),
        ('B.TECH - ECE', 'B.TECH - ECE'),
        ('M.TECH - CSE', 'M.TECH - CSE'),
        ('M.TECH - IT', 'M.TECH - IT'),
        ('M.TECH - ECE', 'M.TECH - ECE'),
        ('MCA', 'MCA'),
    )

    ADMISSION_YEAR_CHOICES = []
    for r in range((datetime.now().year-4), (datetime.now().year+1)):
        ADMISSION_YEAR_CHOICES.append((r,r))

    PASSING_YEAR_CHOICES = []
    for r in range((datetime.now().year), (datetime.now().year+5)):
        PASSING_YEAR_CHOICES.append((r,r))

    REGION = (
        ('Delhi', 'Delhi'),
        ('Outside Delhi', 'Outside Delhi'),
    )

    CATEGORY = (
        ('Unreserved', 'Unreserved'),
        ('OBC', 'OBC'),
        ('SC', 'SC'),
        ('ST', 'ST'),
        ('OTH', 'Other'),
    )

    GENDER = (
        ('Male', 'Male'),
        ('Female', 'Female'),
        ('Others', 'Others'),
    )

    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    enrollment_no = models.CharField(max_length=20, unique=True, null=False, blank=False)
    name = models.CharField(_("Full Name"), max_length=100)
    gender = models.CharField(max_length=11, choices=GENDER)
    date_of_birth = models.DateField(_("Date of birth"), blank=True, null=True)
    college = models.CharField(max_length=10,choices=COLLEGE,default='USICT')
    #institute_code = models.IntegerField(default=0)
    #program_code = models.IntegerField(default=0)
    course = models.CharField(max_length = 20, choices=COURSE)
    admission_year = models.IntegerField(_('Year of Admission'), blank=True, null=True, choices=ADMISSION_YEAR_CHOICES)
    passing_year = models.IntegerField(_('Year of Passing Out'), blank=True, null=True, choices=PASSING_YEAR_CHOICES)
    fathers_name = models.CharField(max_length=100, blank=True, null=True)
    region = models.CharField(max_length=20, choices=REGION)
    category = models.CharField(max_length=20, choices=CATEGORY)
    primary_mobile = models.PositiveIntegerField(_("Mobile Number"), blank=True, null=True, validators=[MaxValueValidator(9999999999)])
    secondary_mobile = models.PositiveIntegerField(_("Alternative Mobile Number"), blank=True, null=True, validators=[MaxValueValidator(9999999999)])
    address = models.TextField(max_length=200, blank=True, null=True)

    def __str__(self):
        return self.user.email

class ExtraInfo(models.Model):

    EDUCATION = (
        ('UP TO 5TH', 'UP TO 5TH'),
        ('UP TO 8TH', 'UP TO 8TH'),
        ('UP TO 10TH', 'UP TO 10TH'),
        ('UP TO 12TH', 'UP TO 12TH'),
        ('UP TO UG', 'UP TO UG'),
        ('UP TO PG', 'UP TO PG'),
        ('ANY OTHER', 'ANY OTHER'),
    )

    FAMILY_INCOME = (
        ('< 50,000', '< 50,000'),
        ('50,000 - 1,00,000', '50,000 - 1,00,000'),
        ('1,00,000 - 2,50,000', '1,00,000 - 2,50,000'),
        ('2,50,000 - 4,00,000', '2,50,000 - 4,00,000'),
        ('4,00,000 - 6,00,000', '4,00,000 - 6,00,000'),
        ('6,00,000 - 10,00,000', '6,00,000 - 10,00,000'),
        ('10,00,000 >', '10,00,000 >'),
    )

    SCHOOL_ATTENDED_12TH = (
        ('GOVT', 'GOVT'),
        ('GOVT AIDED', 'GOVT AIDED'),
        ('SELF FINANCING/ UNAIDED', 'SELF FINANCING/ UNAIDED'),
    )

    BOARD = (
        ('CBSE', 'CBSE'),
        ('State Board', 'State Board'),
        ('NIOS', 'NIOS'),
        ('Madarsa', 'Madarsa'),
        ('Other', 'Other'),
    )

    FATHERS_EMPLOYMENT = (
        ('GOVT Service, PSU', 'GOVT Service, PSU'),
        ('Private service', 'Private service'),
        ('Self employed', 'Self employed'),
        ('Professional', 'Professional'),
        ('Casual Labour', 'Casual Labour'),
        ('Farming, Agri-Labour', 'Farming, Agri-Labour'),
        ('Unemployed', 'Unemployed'),
        ('Other', 'Other'),
    )

    MOTHERS_EMPLOYMENT = (
        ('GOVT Service, PSU', 'GOVT Service, PSU'),
        ('Private service', 'Private service'),
        ('Self employed', 'Self employed'),
        ('Professional', 'Professional'),
        ('Casual Labour', 'Casual Labour'),
        ('Farming, Agri-Labour', 'Farming, Agri-Labour'),
        ('House wife', 'House wife'),
        ('Other', 'Other'),
    )

    RELIGION = (
        ('Hindu', 'Hindu'),
        ('Muslim', 'Muslim'),
        ('Sikh', 'Sikh'),
        ('Christain', 'Christain'),
        ('Jain', 'Jain'),
        ('Buddhist', 'Buddhist'),
        ('Parshi', 'Parshi'),
        ('Any other', 'Any other'),
    )

    student = models.OneToOneField(StudentProfile, on_delete=models.CASCADE)
    address = models.CharField(max_length=1024, blank=True, null=True)
    pincode = models.IntegerField(blank=True, null=True)
    fathers_education = models.CharField(max_length=20, choices=EDUCATION, blank=True, null=True)
    mothers_education = models.CharField(max_length=20, choices=EDUCATION, blank=True, null=True)
    family_income = models.CharField(max_length=20, choices=FAMILY_INCOME, blank=True, null=True)
    school_attended_12th = models.CharField(max_length=20, choices=SCHOOL_ATTENDED_12TH, blank=True, null=True)
    board = models.CharField(max_length=20, choices=BOARD, blank=True, null=True)
    aadhar_number = models.IntegerField(blank=True, null=True, validators=[MaxValueValidator(9999999999999999)])
    religion = models.CharField(max_length=20, choices=RELIGION, blank=True, null=True)
    fathers_employment = models.CharField(max_length=20, choices=FATHERS_EMPLOYMENT, blank=True, null=True)
    mothers_employment = models.CharField(max_length=20, choices=MOTHERS_EMPLOYMENT, blank=True, null=True)


    def __str__(self):
        return self.student.enrollment_no

class MarkSheet(models.Model):
    student = models.OneToOneField(StudentProfile, on_delete=models.CASCADE)
    semester_1 = models.DecimalField(max_digits=5, decimal_places=3, validators=[MaxValueValidator(10.000),MinValueValidator(0.000)],blank=True, null=True)
    semester_2 = models.DecimalField(max_digits=5, decimal_places=3, validators=[MaxValueValidator(10.000),MinValueValidator(0.000)],blank=True, null=True)
    semester_3 = models.DecimalField(max_digits=5, decimal_places=3, validators=[MaxValueValidator(10.000),MinValueValidator(0.000)],blank=True, null=True)
    semester_4 = models.DecimalField(max_digits=5, decimal_places=3, validators=[MaxValueValidator(10.000),MinValueValidator(0.000)],blank=True, null=True)
    semester_5 = models.DecimalField(max_digits=5, decimal_places=3, validators=[MaxValueValidator(10.000),MinValueValidator(0.000)],blank=True, null=True)
    semester_6 = models.DecimalField(max_digits=5, decimal_places=3, validators=[MaxValueValidator(10.000),MinValueValidator(0.000)],blank=True, null=True)
    semester_7 = models.DecimalField(max_digits=5, decimal_places=3, validators=[MaxValueValidator(10.000),MinValueValidator(0.000)],blank=True, null=True)
    semester_8 = models.DecimalField(max_digits=5, decimal_places=3, validators=[MaxValueValidator(10.000),MinValueValidator(0.000)],blank=True, null=True)
    cgpa = models.DecimalField(max_digits=5, decimal_places=3, validators=[MaxValueValidator(10.000),MinValueValidator(0.000)],blank=True, null=True)

    credits_skipped = models.IntegerField(validators=[MinValueValidator(0)], blank=True, null=True)
    backlogs = models.IntegerField(verbose_name = "Number of Backlogs", validators=[MinValueValidator(0)], blank=True, null=True)

    def __str__(self):
        return self.student.enrollment_no
        #return "%s "%s" % (self.student.enrollment_no, self.student.name)

class WorkExperience(models.Model):

    CATEGORY_CHOICE =(
        ('Internship', 'Internship'),
        ('Project', 'Project'),
        ('Training', 'Training'),
        ('Achievement', 'Achievement'),
        ('Other', 'Other'),
    )

    student = models.ForeignKey(StudentProfile, on_delete=models.CASCADE)
    category = models.CharField(choices = CATEGORY_CHOICE, max_length = 15, null=True)
    title = models.CharField(max_length = 50, null=True)
    start_date = models.DateField(_("Starting Date"), null=True)
    end_date = models.DateField(_("Ending Date"), blank=True, null=True)
    url = models.URLField(blank=True, null=True)
    description = models.TextField(max_length = 200, null=True)

    def __str__(self):
        return self.student.enrollment_no

class SchoolEducation(models.Model):

    QUALIFICATION_CHOICE = (
        ('HighSchool', 'High School'),
        ('SeniorSecondary', 'Senior Secondary'),
    )

    YEAR_CHOICES = []
    for r in range((datetime.now().year-15), (datetime.now().year+1)):
        YEAR_CHOICES.append((r,r))

    student = models.ForeignKey(StudentProfile, on_delete=models.CASCADE)
    qualification = models.CharField(choices=QUALIFICATION_CHOICE, max_length=20, null=True)
    year = models.IntegerField(choices=YEAR_CHOICES, null=True, blank=True)
    board = models.CharField(max_length=50, null=True, blank=True)
    school = models.CharField(max_length=100, null=True, blank=True)
    marks = models.CharField(_("Percentage/CGPA"), max_length=5, null=True, blank=True)

    def __str__(self):
        return self.student.enrollment_no

class CollegeEducation(models.Model):
    ADMISSION_YEAR_CHOICES = []
    for r in range((datetime.now().year-4), (datetime.now().year+1)):
        ADMISSION_YEAR_CHOICES.append((r,r))

    PASSING_YEAR_CHOICES = []
    for r in range((datetime.now().year), (datetime.now().year+5)):
        PASSING_YEAR_CHOICES.append((r,r))

    COURSES = (
        ('Graduation', 'Graduation'),
        ('Post-Graduation', 'Post-Graduation'),
        ('PhD', 'PhD'),

faculty/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect, JsonResponse
from django.urls import reverse_lazy, reverse
from django.contrib.auth.decorators import login_required
import json
from django.core import serializers
from account.models import User
from student.models import (
    StudentProfile,
    MarkSheet,
    ExtraInfo,
    WorkExperience,
    SchoolEducation,
    CollegeEducation,
    )

# Create your views here.
@login_required(login_url=reverse_lazy('account:faculty_login'))
def dashboard(request):
    if request.user.is_faculty is False:
        return HttpResponseRedirect(reverse('student:dashboard'))
    else:
    	Students = StudentProfile.objects.all()
    	return render(request, template_name='faculty/faculty_dashboard.html', context = {'Students' : Students })

@login_required(login_url=reverse_lazy('account:faculty_login'))
def filter(request):
	if request.user.is_faculty is False:
		return HttpResponseRedirect(reverse('student:dashboard'))
	else:
		selected_courses = json.loads(request.GET.get('selected_courses'))
		selected_years = json.loads(request.GET.get('selected_years'))


		course_filter = []
		if selected_courses:
			for i in selected_courses:
				course_filter += StudentProfile.objects.filter(course = i)
		else:
			course_filter = StudentProfile.objects.all()

		year_filter = []
		for i in course_filter:
			if selected_years:
				for j in selected_years:
					if str(i.passing_year) == j:
						year_filter += StudentProfile.objects.filter(enrollment_no = i.enrollment_no).values()
						break
			else:
				year_filter += StudentProfile.objects.filter(enrollment_no = i.enrollment_no).values()

		for i in year_filter:
			this_user = User.objects.get(id=i['user_id'])
			this_student = StudentProfile.objects.get(id=i['id'])
			email = this_user.email
			i['email'] = email
			i['course'] = this_student.get_course_display()

		data = {
			'filtered_students': year_filter
		}


		return JsonResponse(data, safe=False)

@login_required(login_url=reverse_lazy('account:faculty_login'))
def studentDetail(request, enr):
	if request.user.is_faculty is False:
		return HttpResponseRedirect(reverse('student:dashboard'))

	else:
		Student = StudentProfile.objects.get(enrollment_no=enr)
		school_education = SchoolEducation.objects.filter(student=Student)
		college_education = CollegeEducation.objects.filter(student=Student)
		internship = WorkExperience.objects.filter(student=Student, category="Internship")
		project = WorkExperience.objects.filter(student=Student, category="Project")
		training = WorkExperience.objects.filter(student=Student, category="Training")
		achievement = WorkExperience.objects.filter(student=Student, category="Achievement")
		other = WorkExperience.objects.filter(student=Student, category="Other")
		marksheet = MarkSheet.objects.filter(student=Student)
		if marksheet:
			marksheet = marksheet[0]


		context = {
        	'student' : Student,
			'school_education': school_education,
			'college_education': college_education,
			'internship': internship,
			'project': project,
			'training': training,
			'achievement': achievement,
			'other': other,
			'marksheet': marksheet,
			}

		return render(request, template_name='faculty/student_detail.html', context=context )

templates/faculty/faculty_dashboard.html
{% extends '../home/base.html' %}
{% block body %}
<link href="https://cdn.datatables.net/1.10.12/css/jquery.dataTables.css" rel="stylesheet" />
<link href="https://cdn.datatables.net/buttons/1.2.2/css/buttons.dataTables.css" rel="stylesheet" />
<link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/css/dataTables.semanticui.min.css"/>
<link rel="stylesheet" href="https://cdn.datatables.net/buttons/1.5.6/css/buttons.semanticui.min.css"/>

<script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.19/js/dataTables.semanticui.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.4.2/js/dataTables.buttons.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.5.6/js/buttons.semanticui.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.32/pdfmake.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.5.6/js/buttons.print.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.32/vfs_fonts.js"></script>
<script src="https://cdn.datatables.net/buttons/1.4.2/js/buttons.html5.min.js"></script>

<div style="padding: 20px;">
  <div class="ui grid" id="faculty-dashboard">
    <div class="three wide column">
      <div>
      <div class="ui card" style="padding: 20px;">
        <div id="filter" class="">
        <h4>Show results for</h4>
        <div id="course" class="">
          <h5>COURSE</h5>
          <p>
            <label>
              <input type="checkbox" class="filled-in" name="courses" value="B.TECH - CSE" />
              <span>B.TECH-CSE</span>
            </label>
          </p>
          <p>
            <label>
              <input type="checkbox" class="filled-in" name="courses" value="B.TECH - IT" />
              <span>B.TECH-IT </span>
          </p>
          <p>
            <label>
              <input type="checkbox" class="filled-in" name="courses" value="B.TECH - ECE" />
              <span>B.TECH-ECE</span>
            </label>
          </p>
          <p>
            <label>
              <input type="checkbox" class="filled-in" name="courses" value="M.TECH - CSE" />
              <span>M.TECH-CSE</span>
            </label>
          </p>
          <p>
            <label>
              <input type="checkbox" class="filled-in" name="courses" value="M.TECH - IT" />
              <span>M.TECH-IT </span>
            </label>
          </p>
          <p>
            <label>
              <input type="checkbox" class="filled-in" name="courses" value="M.TECH - ECE" />
              <span>M.TECH-ECE</span>
            </label>
          </p>
        </div><br>

        <div class="" id="year">
          <h5>BATCH</h5>
          <p>
            <label>
              <input type="checkbox" class="filled-in" name="year" value="2019" />
              <span>2019</span>
            </label>
          </p>
          <p>
            <label>
              <input type="checkbox" class="filled-in" name="year" value="2020" />
              <span>2020</span>
            </label>
          </p>
          <p>
            <label>
              <input type="checkbox" class="filled-in" name="year" value="2021" />
              <span>2021</span>
            </label>
          </p>
          <p>
            <label>
              <input type="checkbox" class="filled-in" name="year" value="2022" />
              <span>2022</span>
            </label>
          </p>
        </div>
      </div><br>
      <a href="" id="filter-button" class="ui blue basic button">Apply</a><br>
      </div>
    </div>
    </div>


    <div class="thirteen wide column">
      <div class="ui card" style="padding: 20px;" id="table-div">
        <table id="student-table" class="ui celled table">
          <thead>
              <tr>
                  <th>ENROLLMENT NO.</th>
                  <th>NAME</th>
                  <th>GENDER</th>
                  <th>COURSE</th>
                  <th>BATCH</th>
                  <th>EMAIL ADDRESS</th>
                  <th>MOBILE NO.</th>
              </tr>
          </thead>
          <tbody>
            {% for student in Students %}
            <tr>
                    <td><a href="{% url 'faculty:student-detail' student.enrollment_no %}">{{ student.enrollment_no }}</a></td>
                    <td>{% if student.name %}
                          {{ student.name }}
                        {% else %}
                        <span class="meta">Not Available</span>
                        {% endif %}
                    </td>
                    <td>{% if student.gender %}
                          {{ student.gender }}
                        {% else %}
                        <span class="meta">Not Available</span>
                        {% endif %}
                    </td>
                    <td>{% if student.course %}
                          {{ student.get_course_display }}
                        {% else %}
                        <span class="meta">Not Available</span>
                        {% endif %}
                    </td>
                    <td>{% if student.get_passing_year_display %}
                          {{ student.get_passing_year_display }}
                        {% else %}
                        <span class="meta">Not Available</span>
                        {% endif %}
                    </td>
                    <td>{{ student.user.email }}</td>
                    <td>{% if student.primary_mobile %}
                          {{ student.primary_mobile }}
                        {% else %}
                        <span class="meta">Not Available</span>
                        {% endif %}
                    </td>
            </tr>
          {% endfor %}
          </tbody>

        </table>
      </div>
    </div>
  </div>
</div>




<script type="text/javascript">
	$(document).ready( function () {
    var table = $('#student-table').DataTable({
        buttons: [
            {
              extend: 'excelHtml5',
              text: 'Download Excel',
              className: 'ui teal basic button',
            },
            {
              extend: 'pdfHtml5',
              text: 'Download PDF',
              className: 'ui teal basic button',
            },
            {
              extend: 'print',
              text: 'Print',
              className: 'ui teal basic button',
            }
        ]
    });

     table.buttons().container()
        .appendTo( $('div.eight.column:eq(0)', table.table().container()) );

    $('.buttons-html5').addClass('ui teal button');


  $('#filter-button').click(function(e){
    e.preventDefault();
    var all_courses = $('[name="courses"]');
    var selected_courses=[];
    for(var i =0; i<all_courses.length; i++){
      if(all_courses[i].checked == true)
        selected_courses.push(all_courses[i].value);
    }
    selected_courses = JSON.stringify(selected_courses);

    var all_years = $('[name="year"]');
    var selected_years = [];
    for(var i=0; i<all_years.length; i++){
      if(all_years[i].checked == true)
        selected_years.push(all_years[i].value);
    }
    selected_years = JSON.stringify(selected_years);

    $.ajax({
        url: '{% url "faculty:filter" %}',
        data: {
          'selected_courses': selected_courses,
          'selected_years': selected_years,
        },
        dataType: 'json',
        success: function (data) {
          students = data.filtered_students;
          table.destroy();
          $('#student-table > tbody').html("");
          for(i=0; i< students.length; i++){
            var url = '{% url "faculty:student-detail"  000 %}'.replace(000, students[i].enrollment_no);
            $('#student-table > tbody').append('<tr><td><a href='+url+'>'+students[i].enrollment_no+'</a></td><td>'+students[i].name+'</td><td>'+students[i].gender+'</td><td>'+students[i].course+'</td><td>'+students[i].passing_year+'</td><td>'+students[i].email+'</td><td>'+students[i].primary_mobile+'  </td></tr>');
            }


            table = $('#student-table').DataTable({
               buttons: [
                {
                  extend: 'excelHtml5',
                  text: 'Download Excel',
                  className: 'ui teal basic button',
                },
                {
                  extend: 'pdfHtml5',
                  text: 'Download PDF',
                  className: 'ui teal basic button',
                },
                {
                  extend: 'print',
                  text: 'Print',
                  className: 'ui teal basic button',
                }
            ]
            });

            table.buttons().container()
            .appendTo( $('div.eight.column:eq(0)', table.table().container()) );

            $('.buttons-html5').addClass('ui teal button');
        }


      });

   });

});

</script>
{% endblock %}